language: c
compiler:
  - gcc
branches:
  only:
    - master
script:
gcc -O2 isprime.c -lm -o isprime
gcc -O2 comparison-sort.c -lm -o comparison-sort
gcc -O2 isprime.c -lm -o isprime
gcc -O2 lis.c -lm -o lis
